// src/components/ThemeToggle.tsx
import { createSignal, onMount } from "solid-js";

type Theme = "dark" | "light";

const STORAGE_KEY = "theme";

function readTheme(): Theme {
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === "light" ? "light" : "dark";
}

export default function ThemeToggle() {
  const [theme, setTheme] = createSignal<Theme>("dark");

  onMount(() => {
    setTheme(readTheme());
  });

  const toggleTheme = () => {
    const next = theme() === "dark" ? "light" : "dark";
    setTheme(next);
    window.localStorage.setItem(STORAGE_KEY, next);
    document.documentElement.dataset.theme = next;
  };

  return (
    <button
      aria-label="Toggle color theme"
      class="theme-toggle"
      data-theme-toggle
      onClick={toggleTheme}
      type="button"
    >
      <span aria-hidden="true">{theme() === "dark" ? "☾" : "☀"}</span>
    </button>
  );
}

// src/components/ThemeToggle.svelte
<script lang="ts">
  import { onMount } from "svelte";

  type Theme = "dark" | "light";
  const STORAGE_KEY = "theme";
  let theme = $state<Theme>("light");

  onMount(() => {
    theme = window.localStorage.getItem(STORAGE_KEY) === "dark" ? "dark" : "light";
  });

  function toggleTheme() {
    theme = theme === "dark" ? "light" : "dark";
    window.localStorage.setItem(STORAGE_KEY, theme);
    document.documentElement.dataset.theme = theme;
  }
</script>

<button
  aria-label="Toggle color theme"
  class="theme-toggle"
  data-theme-toggle
  onclick={toggleTheme}
  type="button"
>
  <span aria-hidden="true">{theme === "dark" ? "☾" : "☀"}</span>
</button>
